# Examples for Mathematical Functions

import math

print("The math ceil function")
print(math.ceil(1.4))
print(math.ceil(1.1))
print(math.ceil(5.3))
print(math.ceil(-2.3))
print(math.ceil(-5.3))
print(math.ceil(22.6))
print(math.ceil(10.0))

# floor(x)
print("The math floor function")
print(math.floor(0.6))
print(math.floor(1.4))
print(math.floor(5.3))
print(math.floor(-5.3))
print(math.floor(22.6))
print(math.floor(10.0))

# degrees(x)
print("The math degree function")
print(math.degrees(8.90))
print(math.degrees(-20))
print(math.degrees(1))
print(math.degrees(90))

# radians(x)
print("The math radians function")
print(math.radians(180))
print(math.radians(100.03))
print(math.radians(-20))

# sin(x)
print("The math sin function")
print(math.sin(0.00))
print(math.sin(-1.23))
print(math.sin(10))
print(math.sin(math.pi))
print(math.sin(math.pi/2))
print(math.pi)

# cos(x)
print("The math cos function")
print(math.cos(0.00))
print(math.cos(-1.23))
print(math.cos(10))
print(math.cos(3.14159265359))

# tan(x)
print("The math tan function")
print(math.tan(90))
print(math.tan(-90))
print(math.tan(45))
print(math.tan(60))

# exp(x)
print("The math exp function")
print(math.exp(65))
print(math.exp(-6.89))

# fabs(x)
print("The math fabs function")
print(math.fabs(-66.43))
print(math.fabs(-7))
print(math.fabs(7))

# factorial(x)
print("The math factorial function")
print(math.factorial(5))
print(math.factorial(9))
print(math.factorial(6))
print(math.factorial(12))

# fmod(x, y)
print("The math fmod function")
print(math.fmod(20.36, 4))
print(math.fmod(20, 3))
print(math.fmod(15, 6.369))
print(math.fmod(-10, 3))

# fsum(values)
print("The math fsum function")
print(math.fsum((26.3, 5698.36)))
print(math.fsum([1, 2, 3, 4, 5]))
print(math.fsum([100, 400, 340, 500]))
print(math.fsum([1.7, 0.3, 1.5, 4.5]))
print(math.fsum((1.7, 0.3, 15, 4.5)))

# log10(x)
print("The math log10 function")
print(math.log10(2.7183))
print(math.log10(2))
print(math.log10(1))

# lof(x, [,base])--- This is ln()
print("The math natural log (ln) function")
print("This is natural log: ", math.log(5.5, 2))
print(math.log(2.7183))
print(math.log(2, 10))
print(math.log(1))

# sqrt(x)
print("The math square root function")
print(math.sqrt(49))
print(math.sqrt(9))
print(math.sqrt(25))
print(math.sqrt(16))
print(math.sqrt(15))

# pow(x, y)
print("The math pow function")
print(math.pow(5, 3))
print(math.pow(9, 3))
print(math.pow(2, 4))

# gcd(x, y)
print("The math gcd function")
print(math.gcd(25, 30))
print(math.gcd(3, 6))
print(math.gcd(6, 12))
print(math.gcd(12, 36))
print(math.gcd(-12, -36))
print(math.gcd(5, 12))
print(math.gcd(10, 0))
print(math.gcd(0, 34))
print(math.gcd(0, 0))

# trunc(x)
print("The math trunc function")
print(math.trunc(15.5676))
print(math.trunc(2.7763487468416984684))
print(math.trunc(8.32))
print(math.trunc(-993154135.29))

# isinf(x)
print("The math isinf function")
print(math.isinf(56))
print(math.isinf(-45.34))
print(math.isinf(+45.34))
print(math.isinf(math.inf))
print(math.isinf(float("nan")))
print(math.isinf(float("inf")))
print(math.isinf(float("-inf")))
print(math.isinf(-math.inf))

# isnan(x)
print("The math isnan function")
print(math.isnan(56))
print(math.isnan(-45.34))
print(math.isnan(+45.34))
print(math.isnan(math.nan))
print(math.isnan(float("nan")))
print(math.isnan(float("inf")))
print(math.isnan(float("-inf")))
print(math.isnan(-math.nan))

# Constrants in math module
# isinf(x)
print("The math constants function")
print("The value of pi is: ", math.pi)
print("The value of e is: ", math.e)
print("The value of inf is: ", math.inf)
print("The value of nan is: ", math.nan)
print("The value of tau is: ", math.tau)







